### ISSUE TITLE
Targeted migrations by migration name

### ISSUE THREAD

**Issue by alekhrycaiko** [3YOURMIND/django-migration-linter#111]
I've ran into a bit of a snag when looking to integrate with your tool, as I have a large body of migrations that are not backwards compatible (but have already been applied). I also cannot safely delete these migrations due to our test suite's reliance on them. I'd also prefer to avoid uploading my migration table in order to run this job with the `--unapplied-migrations` flag.

It'd be great if I could target a list of migrations by name, and have this linter run against those specific migrations.

Would this kind of feature be plausible without the migration history available?

**Comment by David-Wobrock** [comment]
Hi @alekhrycaiko 
Thanks for opening an issue :)

Indeed, deleting migrations is rarely a good idea, since they are needed to re-create the state of the DB from scratch (often for tests, but also new environments).
If having too many migrations is an issue for you, you should checkout migration squashing in Django.

For the linter, there are multiple ways to target specific migrations or a set of migrations. See the detailed options here: https://github.com/3YOURMIND/django-migration-linter/blob/master/docs/usage.md

Among others:
* your suggestion:
> It'd be great if I could target a list of migrations by name, and have this linter run against those specific migrations.

Currently, one can target a list of migrations by file path. I admit that this is not exactly the same, but it is something :) That would be the `--include-migrations-from` option, to which you specify a filename

* If you're using git to version your project, you can build a system that will use the previous release tag for instance, in order to lint added and modified migrations since a certain point in time

* The linter has coarse-grained options for include/excluding apps (but not yet for specific files)
* And it has options to ignore migrations. One option (even if rather brute-force) would be to use the `--ignore-name` option and list all old migrations that you don't want to lint :thinking: 

In the current state, your best bet is probably a file with the paths of the migrations. But, being able to target one (or multiple) specific migration could be something viable to implement. However, some API incompatibility issues have to be taken into account if we'd want to have a linter with the same API as most Django migration commands: `manage.py migration app_name migration_name` (since the only positional argument of the linter is the git identifier)

Hope that helps :)

**Comment by David-Wobrock** [comment]
As mentioned, I think that the `--include-migrations-from` should fix the issue if you are able to put all migration file paths that need linting into one file.
If not, an easy alternative could be to implement the opposite feature: `--exclude-migrations-from` so that you can always avoid linting a specific set of migrations.

Closing for now due to inactivity. Feel free to re-open an issue if you think the solution mentioned above would be helpful if implemented.
