### ISSUE TITLE
Feature request: Add --quiet passed

### ISSUE THREAD

**Issue by theilgaard** [3YOURMIND/django-migration-linter#119]
Add option to quiet out `passed` messages, when no cache has been built yet.

**Comment by David-Wobrock** [comment]
Hi @theilgaard 
Thanks for submitting an issue!

Isn't this cas handle by the `--quiet` option (see documentation here https://github.com/3YOURMIND/django-migration-linter/blob/master/docs/usage.md#command-line-usage) with the `ok` value?
This should filter out all _passed_ migrations from the output.

Does that help?

**Comment by theilgaard** [comment]
Hi @David-Wobrock 

No problem. Unfortunately not, it appears `passed` messages are output to stderr, so we had pipe stderr to `/dev/null` on our build server to not crash the HTTP frontend due to too long logs.

It works fine after the cache has been built.

**Comment by theilgaard** [comment]
It appears the issue is just that `logger.debug()` is used for printing `passed` messages (https://github.com/3YOURMIND/django-migration-linter/blob/e86f8a7df25fcd2b8ceb8a017cbeca0bbf80b8f8/django_migration_linter/sql_analyser/base.py#L132) whereas `self.print_linting_msg(app_label, migration_name, "OK", MessageType.OK)` is used for OK messages.

I can submit a PR later today if you want :-)

**Comment by David-Wobrock** [comment]
Okay, I understand the issue better.
I thought you meant the _linting_ messages, which can be suppressed by using the `--quiet`

So those _passed_ messages should only be displayed when debugging during development on the migration linter, and should not be displayed on your CI indeed :/ I suspected two potential causes:
* either the linter is launched with its verbosity option
* or the logging configuration defines printing debug messages on the build server :thinking: 

The latter could probably be fixed by changing the logger config', if that is an option.

I'm also open for a PR for sure :+1: but I'm currently not sure what kind of change we'd want to operate to help you here :thinking:

**Comment by theilgaard** [comment]
Ah right. 

Yea we are running pytests with debug logging in our configuration, and thus get the debug output from the linter as well. Elevating the logging level isn't really an option, as it would make it harder for us to debug build errors. 

I understand that a PR in this case would be silly, unless you are interested in elevating the `passed` message to the level of the `ok` message of course.

**Comment by David-Wobrock** [comment]
I understand that it wouldn't be convenient to change logging level in your build system, and that's not desirable for the linter also :P 

There are probably multiple ways to fix this. Some ideas:
* I think the Python logging module is flexible enough to specifically change the logging level, or disable logging, for one specific module. Currently the linter instantiates the logging in a module through `logger = logging.getLogger(__name__)`. Maybe it's possible to select this one and disable it. Not tested, but the idea:
```
linter_logger = logging.getLogger('django_migration_linter.sql_analyser.base')
linter_logger.disable()
```
Maybe it would require the linter the configure a more stable logger name. That is potentially a change that we can do to the linter if it would help 👍 

* Here https://github.com/3YOURMIND/django-migration-linter/blob/master/django_migration_linter/management/commands/lintmigrations.py#L106-L109 in the management command we configure the basic config of the linter logging. We could add an option when doing `-v 0` we explicitly disable the linter logging 🤔

**Comment by theilgaard** [comment]
This works as a workaround for now.

```python
# Disable verbose django-migration-linter logging
linter_loggers = [
    "django_migration_linter.sql_analyser.base",
    "django_migration_linter.sql_analyser.analyser",
    "django_migration_linter.migration_linter",
]
for logger_name in linter_loggers:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.ERROR)
```

Setting the verbosity level on the cmdline would be nice, and beats piping to `/dev/null` :-)

**Comment by David-Wobrock** [comment]
Thanks for sharing this @theilgaard !

That's useful, since one easy thing we can do here is commonise the logger name of the linter :)
I opened https://github.com/3YOURMIND/django-migration-linter/issues/129 for this task.

Let's keep this issue open for the improvement you suggest: let's handle `--verbosity 0` correctly and remove all output.
It's a thin line between an enhancement and a bug, because the command line usage already suggests that `-v 0` should work (see https://github.com/3YOURMIND/django-migration-linter/blob/master/docs/usage.md#command-line-usage). Let's call it an improvement 😄
