### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by vanschelven** [3YOURMIND/django-migration-linter#137]
Per https://github.com/3YOURMIND/django-migration-linter/commit/2dc4caadf99c39de491e5d1a6d49485dc9ae15fe there is support for config files, which is also mentioned in the documentation that is linked from the project's homepage. I found it somewhat confusing that the mentioned feature does not seem to work (which it doesn't in 2.4.0)

I have no idea whether everything is stable enough for a new release, of course, so don't feel rushed by this random person on the internet :smile:

**Comment by David-Wobrock** [comment]
Hi @vanschelven 

Thanks for taking interest in the project.

The last changes are not released yet. I'd like to merge one of the two open PRs (they implement the same feature basically) so that it can also be included in 2.5.0 :)
I'll try to merge and then release the next version this weekend at the latest :+1:

**Comment by vanschelven** [comment]
Sounds good to me!

**Comment by David-Wobrock** [comment]
Version 2.5.0 is released :) https://github.com/3YOURMIND/django-migration-linter/releases/tag/v2.5.0

If you use the config file support, please let me know if something is not working as expected. Not sure I tested all edge cases for all types of config files.
If something is missing, we'll be able to do a minor bugfix release :)
