### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by igeligel** [3YOURMIND/django-migration-linter#17]
Let us drop Python 2 support here and use newer Python 3 features like fstrings.

**Comment by David-Wobrock** [comment]
To me, worth dropping support for Python 2 just for syntactic sugar like f-strings is not worth it.
Especially that f-strings came out with Python 3.6, so it would also mean dropping all the former versions.

**Comment by hugovk** [comment]
Here's the pip installs for django-migration-linter from PyPI for June 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  93.75% |             15 |
| 2.7            |   6.25% |              1 |
| Total          |         |             16 |

Source: `pypinfo --start-date 2018-06-01 --end-date 2018-06-30 --percent --markdown django-migration-linter pyversion`

**Comment by David-Wobrock** [comment]
Thank you for the numbers.

As you see, few people downloaded the linter.
Dropping versions now would result in even less people who could possibly be interested in the project.

**Comment by igeligel** [comment]
Do you really think supporting Python 2 is a good idea? Python 3 is now stable enough to be considered production-ready. I think, as a community, we should target Python 3 to just make people and old businesses realize that targeting Python 2 is a bad idea and not sustainable in long-term (support will be dropped 2020 anyway).

**Comment by David-Wobrock** [comment]
Yes, I think it is a good idea to support Python 2. To me, Python 3 has been stable for quite some time, and is definitively production-ready as you say.
I understand your point and I agree that people should move toward Python 3. But imagine a business that is in the process of migrating towards python 3. They are still legitimately using Python 2 since, as you pointed it out, the support is dropped in 2020.

The problem with our discussion is the lack of arguments. For the migration linter, I currently see no advantage of only using Python 3 and dropping Python 2. Is there a feature we could implement *a lot* easier in Python 3 (or only in Python 3)? Or would we just simplify the internals?
From what I see, your argument is dropping Python 2 because we can - which is not valid to me.

I have absolutely no problem with dropping Python 2 for good reasons - and we will drop it for sure once it is deprecated in 2020.

**Comment by krysopath** [comment]
I think we should support python2 as long as python2 is the default interpreter for python in the major OS distributions. Saying that now... but depending on how expensive python2 support will be it might just not be feasible. However https://pythonhosted.org/six/ is the tool for just that. It should not be too expensive.

**Comment by lingmann** [comment]
@David-Wobrock thanks for keeping python 2 support alive for the time being! I am looking into using this linter for a project which is still running python 2. We want to migrate to python 3 of course, but you know time and we had to first migrate to Django 1.11. Also, a more interesting stat for evaluating the potential user-base of this project might be to look at the pip installs for Django itself. I wouldn't be surprised if a large number of users on Django 1.11 or less are still running Python 2.

**Comment by David-Wobrock** [comment]
Hi @lingmann, thank you for your comment. The case you describe is a pretty common one. At my current workplace, we also have the plan to update to newer Python and Django versions. Historical projects, with large legacy, are slow to move and breaking things purposely is not an option.
So dropping Python 2 is not a plan for any time soon for the migration linter.

I would be happy to support older versions of Django, but they are 2 blocking points. First, it would be somewhat counterproductive to work towards older, not supported versions. And second, Django 1.10 support was dropped because the internal Migration API of Django changed too much, and supporting multiple versions was becoming cumbersome in our code.
And it encourages older stacks to slowly update to newer versions ;)

**Comment by hugovk** [comment]
> Also, a more interesting stat for evaluating the potential user-base of this project might be to look at the pip installs for Django itself.

I don't have stats handy per Django version, but here's the total pip installs for PyPI for April 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  38.86% | 1,078,975 |
|      2.7 |  27.45% |   762,206 |
|      3.7 |  21.43% |   595,086 |
|      3.5 |   9.01% |   250,227 |
|      3.4 |   2.03% |    56,461 |
| null     |   1.09% |    30,137 |
|      3.8 |   0.06% |     1,764 |
|      2.6 |   0.05% |     1,320 |
|      3.3 |   0.01% |       381 |
|      3.2 |   0.00% |        24 |
| Total    |         | 2,776,581 |

Source: `pypistats python_minor django --last-month # pip install pypistats`

Over time:

![image](https://user-images.githubusercontent.com/1324225/57600874-a14e8300-7563-11e9-95d1-4dc9e47e76a5.png)

Source: https://dev.to/hugovk/python-version-share-over-time-4-26hm


And an update for django-migration-linter, for April 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.4 |  43.98% |       340 |
|      3.7 |  22.90% |       177 |
| null     |  21.35% |       165 |
|      3.6 |   6.60% |        51 |
|      3.5 |   3.36% |        26 |
|      2.7 |   1.81% |        14 |
| Total    |         |       773 |

Source: `pypistats python_minor django-migration-linter --last-month # pip install pypistats`
