### ISSUE TITLE
Integrate CI service

### ISSUE THREAD

**Issue by igeligel** [3YOURMIND/django-migration-linter#3]
Would be really nice to integrate a CI service like [CircleCI](https://circleci.com/) which would check if our code is still runnable.

We wrote tests already so we can test them there too.

**Comment by David-Wobrock** [comment]
> We wrote tests already so we can test them there too.

If there are more tests written for the linter, could you push them here?

**Comment by David-Wobrock** [comment]
Hi @igeligel ,

I commited a .travis.yml file and tested it on my fork. And it does work.

Could you handle adding CI with Travis (since I don't have access to the 3YOURMIND organisation)? It should work out of the box with the current configuration.
And while you are at it, you could add the little Travis badge to the readme of the project?

Thanks!

**Comment by igeligel** [comment]
It is done now. You can find the badge in the readme.
